clone_depth: 50

branches:
  only:
    - master

image: macos-monterey

environment:
  XCODE_VERSION: 14.1
  LINK_HASH: 41d9aa111f702e78b6fbaee9d3e06dda1db6420d

install:
  - git clone https://github.com/Ableton/link.git $APPVEYOR_BUILD_FOLDER/../link
  - cd $APPVEYOR_BUILD_FOLDER/../link
  - git checkout $LINK_HASH
  - git submodule update --init --recursive
  - cd $APPVEYOR_BUILD_FOLDER
  - sudo xcode-select -s /Applications/Xcode-$XCODE_VERSION.app
  - echo "Link Hash $LINK_HASH"
  - SELECTED_XCODE_VERSION=$(xcodebuild -version) && echo "Xcode Version $SELECTED_XCODE_VERSION"

build_script:
  - make link_dir=../link

artifacts:
  - path: build/output/LinkKit.zip
    name: LinkKit.zip
